### ISSUE TITLE
통합 테스트 코드 작성

### ISSUE THREAD

**Issue by jacobhboy** [sickgyun/sickgyun-server#81]
### 🙌 개선 방향

통합 테스트 코드를 작성하는 일을 시작해보면 어떨까 싶습니다. 빠르게 개발하기 위해 테스트 없이 코드를 작성했고, MVP의 거의 모든 기능을 개발하였습니다. 그리고 적극적인 코드 리팩토링에 들어가기 전인 지금이 테스트 코드를 작성하기에 매우 좋은 시점이라고 생각했습니다.

단위 테스트와 통합 테스트의 도입을 고려하였고, 제가 고려한 트레이드오프는  다음과 같습니다.

상황: 대부분의 기능의 코드가 다 작성되어 있음
[단위 테스트]
장점
- 모든 작은 기능 단위가 잘 동작한다는 것이 증명된다.
- 테스트가 빠르다.
단점
- 시간 소요가 크다.

[통합 테스트]
장점
- 많고 작은 기능 단위들을 한번의 테스트로 테스트할 수 있다.
- 실제 서버의 동작과 거의 유사하게 테스트를 진행할 수 있다.
- 빠르게 작성할 수 있다.
단점
- 모든 기능 단위가 정확히 동작하지 않을 수 있다.
- 테스트가 느리다.

만약 지금 코드를 많이 작성하지 않은 시점이라면 개발하는 작은 기능 단위에 대해서 바로 단위테스트를 작성하는 편이 좋을 것입니다. 그러나 현재는 거의 대부분의 코드가 작성되어져있습니다. 그리고 기능 단위의 이음새 부분도 결국 테스트를 진행해야해서 단위 테스트를 진행해도, 통합 테스트는 필수적이라고 판단했습니다. 그러한 측면에서 통합 테스트와 단위 테스트를 모두 진행한다는 것이 많은 부분에서 중복으로 테스트하는 것을 피할 수 없다고 느꼈습니다. 그렇기에 핵심 기능이 아니면, 단위 테스트를 건너뛰고 통합테스트를 작성하는 편이 좋을 것 같다고 생각하게 되었습니다.

### 🏄‍♂️ 참고 자료

https://uilicious.com/blog/unit-testing-vs-integration-testing/

> Unit tests should be conducted early in the development process to quickly detect any faults and provide feedback on the code before more complex components are built up.

아직 저희가 구상한게 많이 남았지만 early in the development process 라고 느껴지진 않습니다 ㅎ

**Comment by Woongbin06** [comment]
저도 단위 테스트와 통합 테스트 둘 다 진행하는 것보다 통합 테스트만 진행하는 것이 낫다고 생각합니다. 현재 저희는 대부분의 코드를 완성했고 실제 동작하는지도 다 해보았기 때문에 단위 테스트로 이런 작업을 반복하기 보다는 통합 테스트로 빠르게 테스트 코드를 돌리는 것이 더 호율적이라 생각합니다. 통합 테스트를 했을 때 모든 기능 단위가 정확하지 않는 것은 요즘 디버깅 툴이 많이 발전해 디버깅만으로도 충분히 해결할 수 있을 것 같습니다. 그리고 다 완성하고 마지막 인수 테스트로 실제 요구사항에 맞는지 테스트해보면 좋을 것 같습니다.
